name       : ktextaddons
version    : 1.2.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/ktextaddons/ktextaddons-1.2.0.tar.xz : 88126cecc592be4c5ecc0c6641474a4ca846dd1866056ce24bada9eb5d080183
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.devel
summary    : Various text handling addons
description: |
    Text addons (autocorrection, text to speak, grammar checking, text translator, emoticon support)
builddeps  :
    - pkgconfig(Qt5UiPlugin)
    - pkgconfig(Qt5TextToSpeech)
    - karchive-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kxmlgui-devel
    - qtkeychain-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
